name: Tests
on: push
env:
  superviser_repo: Gotfrid/project-superviser
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run playwright:install
      - run: npm run test:ci
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ env.superviser_repo }}
          submodules: true
      - uses: extractions/setup-just@v2
      - run: |
          cd ${{ github.event.repository.name }}
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch
          git checkout ${{ github.ref_name }}
          cd ..
      - run: just test
